import Head from "next/head";
import { useState } from "react";
import type { Add } from "../../contracts/src/";
import { useAccounts, useNetwork } from "../components/useMina";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [zkAppInstance, setZkZppInstance] = useState<Add | null>(null);

  const accountsQuery = useAccounts();
  const networkQuery = useNetwork();

  const onClick = async () => {};

  if (!accountsQuery.isConnected) {
    return (
      <div>
        <button onClick={accountsQuery.connect}>Connect</button>
      </div>
    );
  }

  if (accountsQuery.isLoading || networkQuery.isLoading) {
    return <div>Loading...</div>;
  }

  if (!accountsQuery.accounts) {
    return <div>Please connect to Mina wallet</div>;
  }

  if (networkQuery.network !== "Berkeley-QA") {
    return <div>Please switch to Berkeley-QA network</div>;
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>ZKCred</h1>

        <p className={styles.description}>
          {zkAppInstance ? (
            <button onClick={onClick}>Add</button>
          ) : (
            "Loading..."
          )}
        </p>
      </main>

      <footer className={styles.footer}>
        Created by <a href="https://mono-koto.com/">Mono Koto</a>
      </footer>
    </div>
  );
}
